global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: edge-agents
    metrics_path: /metrics
    static_configs:
      - targets: ["agent:8000"]
        labels: { fleet: techvalley-demo }

  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
